<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <AssemblyName>PotatoMusicPlayer</AssemblyName>
    <RootNamespace>PotatoMusicPlayer</RootNamespace>
    <ApplicationIcon>potato.ico</ApplicationIcon>
    <PackageIcon>potato.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="potato.ico" />
    <Resource Include="potato.png" />
    <Resource Include="assets\speaker\speakers_*.png" />
    <Resource Include="Resources\Icons\speaker_*.png" />
    <Content Include="Resources\Languages\*.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\..\PotatoMusicPlayer\PotatoMusicPlayer\PotatoMusicPlayer\potato.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp" Version="3.9.0" />
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.20" />
    <PackageReference Include="TagLibSharp" Version="2.3.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>

</Project>
